17/03/2021 09:28:35 | SyncInvokeRetourneOptionDemande | SPX_PARAM_SELECT_DONNEREFERENCE:Expiration du délai d'attente. Le délai d'attente s'est écoulé avant obtention d'une connexion du pool. Ceci est probablement dû au fait que toutes les connexions regroupées sont en cours d'utilisation et que la taille maximale du pool a été atteinte.

17/03/2021 09:28:37 | SyncInvokeRetourneFermable | Enregistrement annulé :
Expiration du délai d'attente. Le délai d'attente s'est écoulé avant obtention d'une connexion du pool. Ceci est probablement dû au fait que toutes les connexions regroupées sont en cours d'utilisation et que la taille maximale du pool a été atteinte.



17/03/2021 09:28:37 | SyncInvokeRetourneListeDenominationAll | Enregistrement annulé :
Expiration du délai d'attente. Le délai d'attente s'est écoulé avant obtention d'une connexion du pool. Ceci est probablement dû au fait que toutes les connexions regroupées sont en cours d'utilisation et que la taille maximale du pool a été atteinte.

17/03/2021 09:29:40 | SyncInvokeRetourneCodeConsomateur | Enregistrement annulé :
Expiration du délai d'attente. Le délai d'attente s'est écoulé avant obtention d'une connexion du pool. Ceci est probablement dû au fait que toutes les connexions regroupées sont en cours d'utilisation et que la taille maximale du pool a été atteinte.

17/03/2021 09:29:40 | SyncInvokeChargerLesSecteurs | SPX_PARAM_SELECT_DONNEREFERENCE:Une erreur de niveau transport s'est produite lors de la réception des résultats du serveur. (provider: TCP Provider, error: 0 - Une connexion existante a dû être fermée par l’hôte distant.)

17/03/2021 09:29:40 | SyncInvokeRetourneCodeRegroupement | Enregistrement annulé :
Expiration du délai d'attente. Le délai d'attente s'est écoulé avant obtention d'une connexion du pool. Ceci est probablement dû au fait que toutes les connexions regroupées sont en cours d'utilisation et que la taille maximale du pool a été atteinte.

17/03/2021 09:29:40 | SyncInvokeChargerLesTournees | La référence d'objet n'est pas définie à une instance d'un objet.

17/03/2021 09:33:47 | SyncInvokeChargerLesQartiers | La référence d'objet n'est pas définie à une instance d'un objet.

17/03/2021 09:33:47 | SyncInvokeChargerReglageCompteur | Enregistrement annulé :
Une erreur liée au réseau ou spécifique à l'instance s'est produite lors de l'établissement d'une connexion à SQL Server. Le serveur est introuvable ou n'est pas accessible. Vérifiez que le nom de l'instance est correct et que SQL Server est configuré pour autoriser les connexions distantes. (provider: Named Pipes Provider, error: 40 - Impossible d'ouvrir une connexion à SQL Server)

17/03/2021 09:33:47 | SyncInvokeRetourneToutMarque | Enregistrement annulé :
Une erreur liée au réseau ou spécifique à l'instance s'est produite lors de l'établissement d'une connexion à SQL Server. Le serveur est introuvable ou n'est pas accessible. Vérifiez que le nom de l'instance est correct et que SQL Server est configuré pour autoriser les connexions distantes. (provider: Named Pipes Provider, error: 40 - Impossible d'ouvrir une connexion à SQL Server)

